name: Build and deploy website

on:
    push:
        branches:
            - main
    workflow_dispatch: # Allows manual execution of workflow

jobs:
    build-deploy-website:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        container: "docker://asciidoctor/docker-asciidoctor:latest"
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build site using Asciidoctor
              run: asciidoctor -a webfonts! -o "index.html" "README.adoc"

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: '.'

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1
